coverage:
  status:
    project:
      default:
        target: 80%
ignore:
  - "*Mock.cc"
  - "*Mock.h"
comment:
  layout: "condensed_header, condensed_files, diff, flags, files, condensed_footer"
  behavior: default
  hide_project_coverage: false # [true :: only show coverage on the git diff]
