name: Auto test
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core # Required to execute ReportGenerator
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
          dotnet-quality: "ga"

      - name: Build and Run-Test
        run: |
          cmake -S ${{github.workspace}}/test -B ${{github.workspace}}/test/build
          cmake --build ${{github.workspace}}/test/build
          ctest --test-dir ${{github.workspace}}/test/build

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

